#### general settings
name: glf_original_nf64_mnist # name of the experiment
use_tb_logger: true # use tensorboard or not
model: glf
distortion: sr
scale: 4
gpu_ids: [2] # e.g. [0,1,2,5]

#### datasets
datasets:
  train:
    name: MNIST
    mode: LQGT
    dataroot: 'datasets/mnist'

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    color: RGB
  val:
    name: MNIST
    mode: LQGT
    dataroot: 'datasets/mnist'

#### network structures
network_G:
  which_model_G: GLF_original
# TODO Put params of model here
#  in_nc: 3
#  out_nc: 3
#  nf: 64
#  nb: 23

#### path
path:
#  pretrain_model_G: ../experiments/pretrained_models/GLF_v1.pth
  strict_load: true
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  weight_decay_G: 0
  beta1_G: 0.9
  beta2_G: 0.99
  lr_scheme: MultiStepLR

  niter: 400000
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2
  feature_criterion: l1
  feature_weight: 1

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
