#### general settings
name: glf_original_mnist # name of the experiment
use_tb_logger: false # use tensorboard or not
model: generative
gpu_ids: ~ # [2] # e.g. [0,1,2,5]

#### datasets
datasets:
  train:
    name: MNIST
    dataroot: datasets/mnist
    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 256
  val:
    name: MNIST
    dataroot: datasets/mnist

#### network structures
encoder: # E
  which_model: glf_tiny_encoder
  img_size: 28
  in_ch: 1
  nz: 20

decoder: # D
  which_model: glf_tiny_decoder
  img_size: 28
  out_ch: 1
  nz: 20

flow: # F
  which_model: FlowNet
  stop_gradients: True
  nz: 20
  hidden_size: 64
  nblocks: 4

#### path
path:
  pretrained_encoder: ~
  pretrained_decoder: ~
  pretrained_flow: ~
  resume_state: ~
  strict_load: true

#### training settings: learning rate scheme, loss
train:
  lr_E: !!float 1e-3 # 0 to freeze params
  weight_decay_E: 0
  beta1_E: 0.9
  beta2_E: 0.99

  lr_D: !!float 1e-3 # 0 to freeze params
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99

  lr_F: !!float 1e-3  # 0 to freeze params
  weight_decay_F: !!float 2e-5
  beta1_F: 0.9
  beta2_F: 0.99

  niter: 23500 # ~100 epochs

  lr_scheme: MultiStepLR
  warmup_iter: -1  # no warm up
  lr_steps: [11750] # after every 50 epochs
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1
  add_background_mask: false

  feature_weight: 0

  nll_weight: 1

  manual_seed: 10
  val_freq: !!float 1

#### logger
logger:
  print_freq: 1
  save_checkpoint_freq: !!float 1e4
