#### general settings
name: glf_original_nf64_mnist # name of the experiment
use_tb_logger: true # use tensorboard or not
model: generative
gpu_ids: [2] # e.g. [0,1,2,5]

#### datasets
datasets:
  train:
    name: MNIST
    mode: LQGT
    dataroot: 'datasets/mnist'

    use_shuffle: true
    n_workers: 6  # per GPU
    batch_size: 16
    color: RGB
  val:
    name: MNIST
    mode: LQGT
    dataroot: 'datasets/mnist'

#### network structures
encoder: # E
  which_model: glf_encoder
  img_size: 32
  in_ch: 3
  nz: 256

decoder: # D
  which_model: glf_flow
  img_size: 32
  in_ch: 3
  nz: 256

flow: # F
  which_model: FlowNet
  nz: 256
  hidden_size: 64
  n_blocks: 4

#### path
path:
  pretrained_encoder: ~
  pretrained_decoder: ~
  pretrained_flow: ~
  resume_state_encoder: ~
  resume_state_decoder: ~
  resume_state_flow: ~
  strict_load: true

#### training settings: learning rate scheme, loss
train:
  lr_E: !!float 1e-4
  weight_decay_E: 0
  beta1_E: 0.9
  beta2_E: 0.99

  lr_D: !!float 1e-4
  weight_decay_D: 0
  beta1_D: 0.9
  beta2_D: 0.99

  lr_F: !!float 1e-4
  weight_decay_F: 0
  beta1_F: 0.9
  beta2_F: 0.99

  niter: 400000

  lr_scheme: MultiStepLR
  warmup_iter: -1  # no warm up
  lr_steps: [50000, 100000, 200000, 300000]
  lr_gamma: 0.5

  pixel_criterion: l1
  pixel_weight: !!float 1e-2

  feature_criterion: l1
  feature_weight: 1

  nll_weight: 1

  manual_seed: 10
  val_freq: !!float 5e3

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
